### ISSUE TITLE
The flag 'log_dir' is defined twice

### ISSUE THREAD

**Issue by GabrielLin** [RingBDStack/HabNet#2]
When I run `train.py` in HabNet_MC, I am facing the following issues:
```
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "train.py", line 22, in <module>
    """Path to log folder""")
  File "/home/XXXX/.conda/envs/py36habnet/lib/python3.6/site-packages/tensorflow_core/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/home/XXXX/.conda/envs/py36habnet/lib/python3.6/site-packages/absl/flags/_defines.py", line 270, in DEFINE_string
    return DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/home/XXXX/.conda/envs/py36habnet/lib/python3.6/site-packages/absl/flags/_defines.py", line 103, in DEFINE
    module_name)
  File "/home/XXXX/.conda/envs/py36habnet/lib/python3.6/site-packages/absl/flags/_defines.py", line 128, in DEFINE_flag
    fv[flag.name] = flag
  File "/home/XXXX/.conda/envs/py36habnet/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 438, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from train.py.  Description from first occurrence: directory to write logfiles into
```

Could you help? Thanks.

**Comment by Giser-liu** [comment]
I encountered the same problem, do you have a solution now? Can you tell me? Thank you.

**Comment by GabrielLin** [comment]
@Giser-liu , just remove the related code of defining `log_dir` and set a logging directory yourself. However, after I have fixed this issue, I am facing another issue which I have reported in another thread.
