### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (9,10) (9,9) 

### ISSUE THREAD

**Issue by GabrielLin** [RingBDStack/HabNet#3]
When I run train.py in HabNet_MC, I am facing the following issues:
```
/home/XXXX/miniconda2/envs/py36habnet/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Testing: 100%|██████████| 1000/1000 [00:11<00:00, 88.66it/s]
/home/XXXX/miniconda2/envs/py36habnet/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Testing accuracy = 23.40
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    tf.app.run()
  File "/home/XXXX/miniconda2/envs/py36habnet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/XXXX/miniconda2/envs/py36habnet/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/XXXX/miniconda2/envs/py36habnet/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 276, in main
    save_optimized_presicion(all_test_labels, all_test_y_pred, stats_graph_folder, 'test', epoch)
  File "train.py", line 117, in save_optimized_presicion
    diff = recalls_vstack -recalls_tile
ValueError: operands could not be broadcast together with shapes (9,10) (9,9) 
```

Could you help? Thanks.

**Comment by zhujinqiu** [comment]
我按作者设置的batch，GPU直接爆显存，兄弟，你能跑成功吗这个？

**Comment by zhujinqiu** [comment]
你是多少G的显存？跑habnet我都跑不动，我8G

**Comment by GabrielLin** [comment]
> 你是多少G的显存？跑habnet我都跑不动，我8G

I can run it on an 11GB GPU but facing the above issue.
